### ISSUE TITLE
Script needs to be able to handle `SerializationFailure`s gracefully

### ISSUE THREAD

**Issue by reivilibre** [vector-im/stats#23]
It doesn't sound like the kind of thing that matters since it's a read-only process on the Postgres side, but actually it reads from the secondary and long-running transactions can hold up deletions.
It seems to be that there is a maximum (configurable) delay before Postgres will cancel queries so that it can play the write-ahead logs received from the primary.
Earlier queries from other processes can reduce the grace time given to this process — see https://www.postgresql.org/docs/9.1/runtime-config-replication.html `max_standby_streaming_delay` and friends. In other words, the process might just get unlucky with timing and get booted off, even if it's a short query.

```
psycopg2.errors.SerializationFailure: canceling statement due to conflict with recovery
DETAIL:  User query might have needed to see row versions that must be removed.
```

Suggested approach might be to try a couple of times before giving up?

**Comment by callahad** [comment]
Closing as WONTFIX; we've instead set `max_standby_streaming_delay=-1` on our servers to avoid these "conflict with recovery" issues.
